### ISSUE TITLE
Possible typo in home page

### ISSUE THREAD

**Issue by Pax1601** [yoavain/create-windowless-app#1814]
Hello, hope I'm not being dumb but it looks to me there may be a typo in the repo home page: 

![image](https://github.com/yoavain/create-windowless-app/assets/7738284/c6f433e5-57ea-4fa2-87e5-29b68055e26b)

note it says windowsless instead of windowless. 

Have a good day!

**Comment by yoavain** [comment]
Thanks! fixed
